### ISSUE TITLE
V. User Story 

### ISSUE THREAD

**Issue by DavidHieselmayr** [DavidHieselmayr/Gaias-resurrection#73]
#### Team
@JohnLimHTL 
@FlorianBeckerle 
@FabianHaeubl 
@DavidHieselmayr

#### Datum: 06.04.2021 verschoben auf (20.04.2021)
---
### Stories
- [x] Skript um Bäume und Steine zu setzen #86 @JohnLimHTL @FabianHaeubl 
- [x] Onepager #82 @DavidHieselmayr 
- [ ] Tiere und Pathfinder #83 @FabianHaeubl @JohnLimHTL 
- [ ] Player UI #85 @FabianHaeubl @JohnLimHTL 
  - [ ] Hunger & Wasser #84 @FabianHaeubl 
- [x] bewegungsfähiger Feuer Golem @FlorianBeckerle 

### Story IV #56
- [ ] Strukturen Implementieren (Werkbank, Amboss, Ofen Essen) #65 @FabianHaeubl @JohnLimHTL 
- [ ] Wassersystem/Meer #67 @FabianHaeubl @JohnLimHTL 

### Story III #53 
- [ ] Waffen anpassen #64 @FabianHaeubl 

### Zusätzlich
- [x] 6 neue Baummodelle 
- [x] Neue Buschmodelle 
- [x] Wasser hinzugefügt 
- [x] Unterwassereffekt 
- [x] Crafting System aktuallisiert 
- [x] über 20 neue Items 
- [x] neue Tools mit verschiedenen Stufen 
- [x] Blut System hinzugefügt 
- [x] Sounds für Blut und Verletzung Spieler
- [x] neues Portal Boss 
- [x] Blueprint System (können jetzt gefunden werden)
- [x] Waypoints 
- [x] Death Menü hinzugefügt 
- [x] neue Insel 
- [x] Windsystem für Bäume 
- [x] Huhn Gegner 
- [x] parallels Crafting #90 
- [x] neue Tür für Dungeons #91  
- [x] YouTube Kanal (Video+Banner)

**Comment by DavidHieselmayr** [comment]
Note 1
