### ISSUE TITLE
VI. Sprint 

### ISSUE THREAD

**Issue by DavidHieselmayr** [DavidHieselmayr/Gaias-resurrection#99]
#### Team
@JohnLimHTL 
@FlorianBeckerle 
@FabianHaeubl 
@DavidHieselmayr

#### Datum: 01.06.202
---
[Fertigstellungsgrad](https://github.com/DavidHieselmayr/Gaias-resurrection/milestone/1)
### Stories
- [ ] Abschlussvideo #98 
- [ ] Projektabschluss Bericht #97 
- [ ] Download über Cloud ermöglichen #96 
- [ ] Stamina Balance #100 
- [ ] Ressourcen abbauen/Schaden #101
- [ ] Dungeon ausbauen #102
- [ ] Verbesserung Boss Feuergolem #103
- [ ] Verbesserung OnePager #105
- [ ] Abschlusstermin !important #106

**Comment by DavidHieselmayr** [comment]
[Fertigstellungsgrad](https://github.com/DavidHieselmayr/Gaias-resurrection/milestone/1)
